// Generates src/generated/options.ts from webui/shared/options.schema.json.
// The schema is the single source of truth: never edit the generated file.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = resolve(here, "../../shared/options.schema.json");
const target = resolve(here, "../src/generated/options.ts");
const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

const header = `// GENERATED by scripts/generate-options.mjs from
// webui/shared/options.schema.json. Do not edit by hand.
`;

const body = `
export type OptionUi = "simple" | "advanced" | "hidden";

export interface OptionSpec {
  flag: string;
  key: string;
  type: string;
  group: string;
  ui: OptionUi;
  label?: string;
  help?: string;
  role?: string;
  default?: unknown;
  min?: number;
  max?: number;
  multiple_of?: number;
  values?: string[];
  backends?: string[];
  short?: string;
  asset_kind?: string;
  reference_kind?: string;
  repeatable?: boolean;
  required?: boolean;
  arity?: number;
}

export const OPTIONS: OptionSpec[] = ${JSON.stringify(schema.options, null, 2)};

export const CONSTANTS = ${JSON.stringify(schema.constants, null, 2)} as const;

export const CANVAS_PRESETS = ${JSON.stringify(schema.canvas_presets, null, 2)};

export const QUALITY_PRESETS = ${JSON.stringify(schema.quality_presets, null, 2)};

export const REFERENCE_RULES = ${JSON.stringify(schema.references, null, 2)};

export const SLOWER_FLAGS: string[] = OPTIONS.filter(
  (option) => option.group === "parity",
).map((option) => option.flag.slice(2));

export function optionByKey(key: string): OptionSpec | undefined {
  return OPTIONS.find((option) => option.key === key);
}
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, header + body);
console.log(`generated ${target} from ${schema.options.length} options`);
